# Generated by Django 5.0.3 on 2024-04-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_status_projectteam_projectmodule_task_usertask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodule',
            old_name='status',
            new_name='status_name',
        ),
    ]
